id = "supertheme4"
name = "supertheme4"
version = "0.0.2"
schema_version = 1
authors = ["superkacper4 <kucza06@wp.pl>"]
description = "Theme inspired with Sublime Mariana for web dev."
repository = "https://github.com/superkacper4/supertheme4"
